export const ADD_PRODUCT = 'ADD_PRODUCT';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';

export  const DELETE_ITEM = 'DELETE_ITEM';

export const DECREASE_PRODUCT_QUANTITY = 'DECREASE_PRODUCT_QUANTITY';